# Generated by Django 4.1.5 on 2023-01-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nome')),
                ('age', models.IntegerField(default=0, verbose_name='idade')),
                ('description', models.CharField(max_length=255, verbose_name='descrição')),
                ('image', models.ImageField(upload_to='images/', verbose_name='foto')),
            ],
            options={
                'db_table': 'cats',
            },
        ),
    ]
